---
- include_vars: vault.yml

- name: Ensure .ssh dir exist
  file: >
    path: /home/{{remote_user}}/.ssh
    state: directory

- name: Copy github private key
  copy: >
    content: "{{github_private_key_content}}"
    dest: "/home/{{remote_user}}/.ssh/github"
    owner: "{{remote_user}}"
    group: "{{remote_user}}"
    mode: 0600
  no_log: true
  become: true

- name: Make .config
  blockinfile: >
    dest: /home/{{remote_user}}/.ssh/config
    owner: {{remote_user}}
    group: {{remote_user}}
    mode: 0600
    block: |
      Host github.com
          HostName github.com
          User git
          IdentityFile ~/.ssh/github
  become: yes